data_dir: "data"

spacings:
  original: [5.0, 0.4121, 0.4121]
  target:   [1.0, 1.0, 1.0]

window:
  level: 40
  width: 80
  experiments:
    - [0, 80]
    - [0, 200]
    - [-40, 160]

shape:
  volume: [140, 250, 250]
  slice:  [250, 250]

projections:
  axes: [0,1,2]   # Z, Y, X
  methods: [mip, aip, mid]

# 히스토그램 시각화 옵션
# SHOW_HIST: 볼륨 값 분포를 시각화할지 여부
# HIST_BINS: 히스토그램의 막대 수
# HIST_EXPS: W_EXP 리스트 중 어떤 실험 채널을 분석할지 지정
# EQUALIZE_HIST: True 시, 히스토그램 균등화(equalization) 후 원본 vs 균등화된 분포 비교
visualization:
  show_hist: true       # 히스토그램 시각화 여부
  hist_bins: 100        # 히스토그램 bin 개수
  hist_exps: [0]        # W_EXP 리스트 중 시각화할 인덱스
  equalize_hist: true  # 히스토그램 균등화 여부

  show_proj: true       # 프로젝션 비교 시각화 여부
  proj_axes: [0,1,2]    # 프로젝션 축 목록
  proj_methods: [mip, aip, mid]  # 프로젝션 방식




